org: spalacioc05
app: lab3-serverless-libros
service: lab3-serverless-libros

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    LIBROS_TABLE: ${self:service}-libros-${sls:stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [LibrosTable, Arn]

functions:
  crear:
    handler: handler.crear
    events:
      - httpApi:
          path: /libros
          method: post

  listar:
    handler: handler.listar
    events:
      - httpApi:
          path: /libros
          method: get

  obtener:
    handler: handler.obtener
    events:
      - httpApi:
          path: /libros/{id}
          method: get

  actualizar:
    handler: handler.actualizar
    events:
      - httpApi:
          path: /libros/{id}
          method: put

  eliminar:
    handler: handler.eliminar
    events:
      - httpApi:
          path: /libros/{id}
          method: delete

resources:
  Resources:
    LibrosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.LIBROS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

plugins:
  - serverless-offline
